### ISSUE TITLE
Key extraction on macOS

### ISSUE THREAD

**Issue by legendofmi** [jonsth131/ggtool#1]
Would this also work with macOS version? Or it’s only fir Windows?

**Comment by r1sc** [comment]
I dont' know, I don't own the mac-version so I can't test it. But the code searches for a byte-pattern so chances are it will work on mac binaries as well. Try it and report back.

**Comment by legendofmi** [comment]
I will give it a go! Thanks for the reply!

**Comment by legendofmi** [comment]
I tried extracting keys from the file "Return to Monkey Island" inside "Return to Monkey Island.app", but got the error:
`./ggtool extract-keys "Return to Monkey Island"    `
thread 'main' panicked at 'Failed to write keys/key1.bin: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ggtool/src/main.rs:32:48

File tree of the package below:
<img width="622" alt="Screenshot 2022-09-29 at 20 47 29" src="https://user-images.githubusercontent.com/94787966/193129336-fdb4fcdf-593c-431e-b80f-680a4ce28c27.png">

**Comment by legendofmi** [comment]
It seems it worked, so far I managed to extract the keys and the list of the files inside the ggpack.

I was having some issues extracting the keys until I realised I had to create the "keys" folder otherwise, it would not extract them.

**Comment by legendofmi** [comment]
Extraction is working on macOS. I was able to extract the files, but the ".ktxbz" files are not being converted to PNG when I extract them, even though I used "decompress_ktx" to build the ggtool.

**Comment by r1sc** [comment]
Great! See the readme on how to compile with png conversion support

**Comment by r1sc** [comment]
Did you get an error or what happened? It should spit out both the ktx and a png

**Comment by legendofmi** [comment]
I got the following error and the ktxbz file got extracted:
```
Extracting Locksmith1-hd.ktxbz. Size = 11416, offset = 1088884480
Inflating...
Decompressing BPTC texture...
thread 'main' panicked at 'Contexts must be destroyed explicitly with `destroy_context`!', /Users/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/surfman-0.4.3/src/platform/macos/cgl/context.rs:95:13
```


There are other files that aren't getting extracted:
```
Extracting MonkeyHead2-hd.ktxbz. Size = 9530480, offset = 1006135040
Inflating...
thread 'main' panicked at 'Failed to inflate compressed data: "unknown ZLIB method CM=0x0"', libdinky/src/ggpack.rs:136:52
```

**Comment by r1sc** [comment]
> I got the following error and the ktxbz file got extracted:
> 
> ```
> Extracting Locksmith1-hd.ktxbz. Size = 11416, offset = 1088884480
> Inflating...
> Decompressing BPTC texture...
> thread 'main' panicked at 'Contexts must be destroyed explicitly with `destroy_context`!', /Users/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/surfman-0.4.3/src/platform/macos/cgl/context.rs:95:13
> ```
> 
> There are other files that aren't getting extracted:
> 
> ```
> Extracting MonkeyHead2-hd.ktxbz. Size = 9530480, offset = 1006135040
> Inflating...
> thread 'main' panicked at 'Failed to inflate compressed data: "unknown ZLIB method CM=0x0"', libdinky/src/ggpack.rs:136:52
> ```

Would you like to create two separate issues with these problem, so we can track and fix them?

For housekeeping I'll close this issue since the key extraction seems to be resolved on macOS binaries. 

Thanks for your help testing this out!
