### ISSUE TITLE
Release?!

### ISSUE THREAD

**Issue by Zibri** [jonsth131/ggtool#6]
Can you please release windows or linux binaries?

**Comment by Zibri** [comment]
[ggtool.zip](https://github.com/jonsth131/ggtool/files/9954409/ggtool.zip)
I compiled this for Linux. A windows version would be nice too..

**Comment by jonsth131** [comment]
Releases are now set up to release Linux, Windows and macOS binaries without the ktx-decompress feature.

I've only tested the Linux binary, if you are able to test the Windows binary that would be appreciated.

**Comment by Zibri** [comment]
> Releases are now set up to release Linux, Windows and macOS binaries without the ktx-decompress feature.
> 
> I've only tested the Linux binary, if you are able to test the Windows binary that would be appreciated.

Sure! It would be nice if it also could split the Music bank file...

**Comment by Zibri** [comment]
> Releases are now set up to release Linux, Windows and macOS binaries without the ktx-decompress feature.
> 
> I've only tested the Linux binary, if you are able to test the Windows binary that would be appreciated.

Just tested the windows msvc version and it works.

**Comment by jonsth131** [comment]
Great, thanks! Regarding the bank files, I'll open a new issue and take a look.
