### ISSUE TITLE
Works for all files except the first one...

### ISSUE THREAD

**Issue by Zibri** [jonsth131/ggtool#7]
$ ~/ggtool extract-files Weird.ggpack1a "*" extracted/
Extracting AbandonedPirateCamp.wimpy. Size = 8170, offset = 16
Extracting AbandonedShip.wimpy. Size = 14696, offset = 8192
Extracting Alley.wimpy. Size = 4082, offset = 22896
Extracting AlleyPart5.wimpy. Size = 4023, offset = 26992
Extracting BLANK.yack. Size = 227, offset = 31024
Extracting BarPirates.yack. Size = 6338, offset = 31264
Extracting BarebonesIsland.wimpy. Size = 7221, offset = 37616
Extracting BelowCliff.wimpy. Size = 12181, offset = 44848
Extracting BelowCliff.yack. Size = 17840, offset = 57040
Extracting Blizzard.emitter. Size = 2362, offset = 74880
Extracting BlizzardOverview.emitter. Size = 2683, offset = 77248
Extracting BlizzardQuarry.emitter. Size = 2364, offset = 79936
Extracting Bonfire.emitter. Size = 4051, offset = 82304
Extracting Bonfire2.emitter. Size = 8135, offset = 86368
Extracting BonfireDistant.emitter. Size = 7814, offset = 94512
Extracting BonfireScumm.emitter. Size = 6870, offset = 102336
Extracting BottleBubbles.emitter. Size = 2251, offset = 109216
Extracting BrrrMudaOverview.wimpy. Size = 3998, offset = 111472
thread 'main' panicked at '1 is not a known GGValueType', libdinky/src/directory.rs:34:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

list-files works...

[
  "AbandonedPirateCamp.wimpy",
  "AbandonedShip.wimpy",
  "Alley.wimpy",
  "AlleyPart5.wimpy",
  "BLANK.yack",
  "BarPirates.yack",
  "BarebonesIsland.wimpy",
  "BelowCliff.wimpy",
  "BelowCliff.yack",
  "Blizzard.emitter",
  "BlizzardOverview.emitter",
  "BlizzardQuarry.emitter",
  "Bonfire.emitter",
  "Bonfire2.emitter",
  "BonfireDistant.emitter",
  "BonfireScumm.emitter",
  "BottleBubbles.emitter",
  "BrrrMudaOverview.wimpy",
  "Bubbles.emitter",
  "BubblesBlowfish.emitter",
  "BubblesPlungeFloodedCave.emitter",
  "BubblesPlungeOffshore.emitter",
  "BubblesPlungeUnderShip.emitter",
  "BubblesStream.emitter",

too long to paste it all...

**Comment by jonsth131** [comment]
Thanks for the report.

The latest change fixes this issue by adding a null value type when reading the GGDict.
